/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.7.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth_email from "../auth/email.js";
import type * as convexLuciaAuth_convexAdapter from "../convexLuciaAuth/convexAdapter.js";
import type * as convexLuciaAuth_convexAuthHelpers from "../convexLuciaAuth/convexAuthHelpers.js";
import type * as convexLuciaAuth_lucia from "../convexLuciaAuth/lucia.js";
import type * as course_details from "../course/details.js";
import type * as http from "../http.js";
import type * as payments_stripe from "../payments/stripe.js";
import type * as payments_stripeOperations from "../payments/stripeOperations.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "auth/email": typeof auth_email;
  "convexLuciaAuth/convexAdapter": typeof convexLuciaAuth_convexAdapter;
  "convexLuciaAuth/convexAuthHelpers": typeof convexLuciaAuth_convexAuthHelpers;
  "convexLuciaAuth/lucia": typeof convexLuciaAuth_lucia;
  "course/details": typeof course_details;
  http: typeof http;
  "payments/stripe": typeof payments_stripe;
  "payments/stripeOperations": typeof payments_stripeOperations;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
